# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find pairs of points within fixed cutoff
#'
#' @param x Matrix of positions where a column corrresponds to a point
#' @param npartitions Number of partitions to generate
#' @param dcell Side-length if square grid cell used to bin points
#'
#' @return List of bounadries
#' @export
#'
#' @examples
#' x <- matrix(rnorm(5000), nrow=2)
#' orb(x, npartitions=8, dcell=0.15)
orb <- function(x, npartitions, dcell) {
    .Call(`_orbr_orb`, x, npartitions, dcell)
}

